name: Tests
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-16.04
    #environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn compile
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          ALCHEMY_PROJECT_ID: ${{ secrets.ALCHEMY_PROJECT_ID }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          BLOCK_NO: ${{ secrets.BLOCK_NO }}
          DIMENSION_ALPHA: ${{ secrets.DIMENSION_ALPHA }}
          DIMENSION_BETA: ${{ secrets.DIMENSION_BETA }}
          DIMENSION_MAX: ${{ secrets.DIMENSION_MAX }}
          DIMENSION_EPSILON: ${{ secrets.DIMENSION_EPSILON }}
          DIMENSION_LAMBDA: ${{ secrets.DIMENSION_LAMBDA }}
      - run: yarn test
