name: Tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    strategy:
          matrix:
            node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn compile && yarn test
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          ALCHEMY_PROJECT_ID: ${{ secrets.ALCHEMY_PROJECT_ID }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          BLOCK_NO: ${{ secrets.BLOCK_NO }}
          DIMENSION_ALPHA: ${{ secrets.DIMENSION_ALPHA }}
          DIMENSION_BETA: ${{ secrets.DIMENSION_BETA }}
          DIMENSION_MAX: ${{ secrets.DIMENSION_MAX }}
          DIMENSION_EPSILON: ${{ secrets.DIMENSION_EPSILON }}
          DIMENSION_LAMBDA: ${{ secrets.DIMENSION_LAMBDA }}
          TOKENS_USDC_DECIMALS: ${{ secrets.TOKENS_USDC_DECIMALS }}
          TOKENS_CADC_DECIMALS: ${{ secrets.TOKENS_CADC_DECIMALS }}
          TOKENS_EURS_DECIMALS: ${{ secrets.TOKENS_EURS_DECIMALS }}
          TOKENS_XSGD_DECIMALS: ${{ secrets.TOKENS_XSGD_DECIMALS }}
